config/routes.rb
Rails.application.routes.draw do
  namespace :confirmation do
    get "instagram_tool/:id", to: "instagram_tool#show"
    patch "instagram_tool/update/:id", to: "instagram_tool#update", as: "instagram_tool_update_path"
  end

  resources :instagram_tools

  root to: "instagram_tools#new"
  get 'search', to: 'instagram_tools#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instagram_tool.rb
class InstagramTool < ApplicationRecord

  def self.add_hash_value
    encryptor = ::ActiveSupport::MessageEncryptor.new(ENV["SECRET_HASH"], cipher: 'aes-256-cbc')
    value = encryptor.encrypt_and_sign(self.id)
    self.update(hash_value: value)
  end
  
  validates :AgencyName,:LoginId,:PassWord,:ContractDate ,:CustomerName,
            :CustomerAddress,:CustomerPhone, :payment, presence: true
  validates :LoginId, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include InstagramToolsHelper
end

app/controllers/confirmation/instagram_tool_controller.rb
class Confirmation::InstagramToolController < ApplicationController

  def show
    redirect_to_root
    @instagram_tool = get_instagram_tool(params[:id])
  end

  def update
    @instagram_tool = InstagramTool.find(params[:id])
    @instagram_tool.update(issue_flag: true)
    send_created_mails(@instagram_tool)
    redirect_to root_path
  end

  private
    def exist_id?
      !InstagramTool.find_by(hash_value: params[:id], issue_flag: false)
    end

    def redirect_to_root
      redirect_to root_path if exist_id?
    end

end

app/controllers/instagram_tools_controller.rb
class InstagramToolsController < ApplicationController
  before_action :set_instagram_tool, only: [:show, :edit, :update, :destroy]


  def index
    @q = InstagramTool.ransack(params[:q])
    @instagram_tools = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def search
    @q = InstagramTool.ransack(params[:q])
    @instagram_tools = @q.result.page(params[:page]).per(10)
    render :template => "instagram_tools/index"
  end

  def show;end

  def new
    @instagram_tool = InstagramTool.new
  end

  def edit;end

  def create
    @instagram_tool = InstagramTool.new(instagram_tool_params)
    if @instagram_tool.save
      # なぜかモデルのメソッドが認識されないから苦渋の選択としてコントローラーに書く
      encryptor = ::ActiveSupport::MessageEncryptor.new(ENV["SECRET_HASH"], cipher: 'aes-256-cbc')
      value = encryptor.encrypt_and_sign(@instagram_tool.id)
      @instagram_tool.update(hash_value: value)
      send_new_apply_mails(@instagram_tool)
      render "layouts/thanks"
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @instagram_tool.update(instagram_tool_params)
        format.html { redirect_to @instagram_tool, notice: 'Instagram tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @instagram_tool }
      else
        format.html { render :edit }
        format.json { render json: @instagram_tool.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @instagram_tool.destroy
    respond_to do |format|
      format.html { redirect_to instagram_tools_url, notice: 'Instagram tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def search_params
      params.require(:q).permit!
    end

    def set_instagram_tool
      @instagram_tool = InstagramTool.find(params[:id])
    end

    def instagram_tool_params
      params.require(:instagram_tool).permit( :AgencyName,
                                              :LoginId,
                                              :PassWord,
                                              :ContractDate,
                                              :CustomerName,
                                              :CustomerAddress,
                                              :CustomerPhone,
                                              :payment,
                                              :issue_flag,
                                              :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmation/instagram_tool_helper.rb
module Confirmation::InstagramToolHelper
end

app/helpers/instagram_tools_helper.rb
module InstagramToolsHelper

  def get_instagram_tool(hash_value)
    id = decryption(hash_value)
    InstagramTool.find(id)
  end

  def decryption(hash_value)
    encryptor = ::ActiveSupport::MessageEncryptor.new(ENV["SECRET_HASH"], cipher: 'aes-256-cbc')
    encryptor.decrypt_and_verify(hash_value)
  end

  def send_new_apply_mails(customer)
    NotificationMailer.send_new_apply_to_lim(customer).deliver_now
    NotificationMailer.send_new_apply_to_upper(customer).deliver_now
    NotificationMailer.send_new_apply_to(customer).deliver_now
  end

  def send_created_mails(customer)
    NotificationMailer.send_created_to(customer).deliver_now
    NotificationMailer.send_created_to_upper(customer).deliver_now
    NotificationMailer.send_created_to_lim(customer).deliver_now
  end

end

app/views/confirmation/instagram_tool/show.html.erb
<h1>Confirmation::InstagramTool#show</h1>
<p>Find me in app/views/confirmation/instagram_tool/show.html.erb</p>

<%= form_for @instagram_tool, url: confirmation_instagram_tool_update_path_path(@instagram_tool.id) do |f| %>
  <%= f.hidden_field :id, value: @instagram_tool.id %>
  <labe><%= @instagram_tool.LoginId %></labe>のアカウントを発行しましたか？

  <%= f.submit "発行しました" %>
  *ボタンが押されると登録されたお客様のメールアドレスへ通知メールが送信されます。
  再度ご確認ください。
<% end %>

app/views/instagram_tools/_form.html.erb
<%= form_with(model: instagram_tool, local: true) do |form| %>
  <% if instagram_tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instagram_tool.errors.count, "箇所") %>入力に不備があります</h2>

      <ul>
      <% instagram_tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form>
    <div class="form-group">
    <label>代理店名</label>
      <%= form.text_field :AgencyName, id: :instagram_tool_AgencyName, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>ログインID</label>
      <%= form.text_field :LoginId, id: :instagram_tool_LoginId, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>パスワード</label>
      <%= form.password_field :PassWord, id: :instagram_tool_PassWord, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>契約日</label>
      <%= form.date_select :ContractDate, id: :instagram_tool_ContractDate, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>顧客名</label>
      <%= form.text_field :CustomerName, id: :instagram_tool_CustomerName, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>メールアドレス</label>
      <%= form.text_field :email, id: :instagram_tool_email, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>顧客住所</label>
      <%= form.text_field :CustomerAddress, id: :instagram_tool_CustomerAddress, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>顧客電話番号</label>
      <%= form.number_field :CustomerPhone, id: :instagram_tool_CustomerPhone, class:"form-control"%>
    </div>

    <div class="form-group">
    <label>支払い方法</label>
      <%= form.text_field :payment, id: :instagram_tool_payment, class:"form-control"%>
    </div>

    <div class="actions">
      <%= form.submit "送信する", class:"btn btn-info"%>
    </div>
    <% end %>
  </form>

app/views/instagram_tools/edit.html.erb
<h1>Editing Instagram Tool</h1>

<%= render 'form', instagram_tool: @instagram_tool %>

<%= link_to 'Show', @instagram_tool %> |
<%= link_to 'Back', instagram_tools_path %>

app/views/instagram_tools/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="instagram_tool_table">
    <div class="title_and_form">
      <h1>顧客リスト</h1>

      <%= search_form_for(@q, url:search_path) do |f|%>
        <%= f.label :CustomerName_cont, '顧客名前' %>
        <%= f.search_field :CustomerName_cont%>
        <%= f.submit class:"btn btn-primary" %>
      <% end %>
    </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>代理店名</th>
        <th>ログインID</th>
        <th>パスワード</th>
        <th>契約日</th>
        <th>顧客名</th>
        <th>メールアドレス</th>
        <th>顧客住所</th>
        <th>顧客電話番号</th>
        <th>支払い方法</th>
        <th>発行状況</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @instagram_tools.each do |instagram_tool| %>
        <tr>
          <td><%= instagram_tool.AgencyName %></td>
          <td><%= instagram_tool.LoginId %></td>
          <td><%= instagram_tool.PassWord %></td>
          <td><%= instagram_tool.ContractDate %></td>
          <td><%= instagram_tool.CustomerName %></td>
          <td><%= instagram_tool.email %></td>
          <td><%= instagram_tool.CustomerAddress %></td>
          <td><%= instagram_tool.CustomerPhone %></td>
          <td><%= instagram_tool.payment %></td>
          <th><%= instagram_tool.issue_flag ? "発行済み" : "未発行" %></th>
          <td><%= link_to 'Show', instagram_tool %></td>
          <td><%= link_to 'Edit', edit_instagram_tool_path(instagram_tool) %></td>
          <td><%= link_to 'Destroy', instagram_tool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= paginate @instagram_tools %>
  <%= link_to 'New Instagram Tool', new_instagram_tool_path %>
</div>

app/views/instagram_tools/new.html.erb
<div class="new_form">
  <h1 class="new_title" >エターナルフォース申し込みフォーム</h1>
  <%= render 'form', instagram_tool: @instagram_tool %>
</div>

app/views/instagram_tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agencyname:</strong>
  <%= @instagram_tool.AgencyName %>
</p>

<p>
  <strong>Loginid:</strong>
  <%= @instagram_tool.LoginId %>
</p>

<p>
  <strong>Password:</strong>
  <%= @instagram_tool.PassWord %>
</p>

<p>
  <strong>Contractdate:</strong>
  <%= @instagram_tool.ContractDate %>
</p>

<p>
  <strong>Customername:</strong>
  <%= @instagram_tool.CustomerName %>
</p>

<p>
  <strong>Customeraddress:</strong>
  <%= @instagram_tool.CustomerAddress %>
</p>

<p>
  <strong>Customerphone:</strong>
  <%= @instagram_tool.CustomerPhone %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @instagram_tool.payment %>
</p>

<%= link_to 'Edit', edit_instagram_tool_path(@instagram_tool) %> |
<%= link_to 'Back', instagram_tools_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalseTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/thanks.html.erb
<h3>ありがとうございました</h3>
<p>担当のものから連絡が来るまでしばらくお待ちください</p>
<%= link_to "入力画面へ", root_path%>